### ISSUE TITLE
Add the Lang entry to the PDF catalog

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/asciidoctor-pdf.js#114]
`pdf-lib` does not have a nice API to set the `Lang` attribute but we should be able to do it using the low-level API to add the Lang entry in the [PDFCatalog](https://pdf-lib.js.org/docs/api/classes/pdfdocument#catalog).

https://www.w3.org/TR/WCAG20-TECHS/PDF16.html

Follow-up of: https://github.com/Mogztter/asciidoctor-pdf.js/pull/112

**Comment by ahus1** [comment]
I've looked at the document properties in Adobe Reader for basic-example.pdf and can't find the language. I expect it to be filled with a value, but it isn't. Any idea? How did you test?

![image](https://user-images.githubusercontent.com/3957921/68678880-17f22a80-055f-11ea-8bad-fa69262b1469.png)

**Comment by Mogztter** [comment]
I used `exiftool`:

```
exiftool -a -G1 examples/document/basic-example.pdf           
[ExifTool]      ExifTool Version Number         : 10.80
[System]        File Name                       : basic-example.pdf
[System]        Directory                       : examples/document
[System]        File Size                       : 84 kB
[System]        File Modification Date/Time     : 2019:11:12 15:46:46+01:00
[System]        File Access Date/Time           : 2019:11:12 15:46:46+01:00
[System]        File Inode Change Date/Time     : 2019:11:12 15:46:46+01:00
[System]        File Permissions                : rw-rw-r--
[File]          File Type                       : PDF
[File]          File Type Extension             : pdf
[File]          MIME Type                       : application/pdf
[PDF]           PDF Version                     : 1.7
[PDF]           Linearized                      : No
[PDF]           Page Count                      : 7
[PDF]           Language                        : en
[PDF]           Creator                         : Asciidoctor PDF 1.0.0-alpha.3
[PDF]           Producer                        : Doc Writer
[PDF]           Create Date                     : 1970:01:01 00:00:00Z
[PDF]           Modify Date                     : 1970:01:01 00:00:00Z
[PDF]           Title                           : Document Title
[PDF]           Author                          : Doc Writer
[PDF]           Subject                         : 
```

Could you please try with the attached pdf? [language-en.pdf](https://github.com/Mogztter/asciidoctor-pdf.js/files/3836672/language-en.pdf) (not generated by Asciidoctor PDF)

**Comment by ahus1** [comment]
I tried the attached PDF language-en.pdf, and it also doesn't show the language. So it's probably only me.

**Comment by Mogztter** [comment]
My PDF reader does not show the language that's why I used `exiftool`.

> I tried the attached PDF language-en.pdf, and it also doesn't show the language. So it's probably only me.

That's weird. 
I took the PDF from the PDF16 specification:

> Note: Acrobat includes 16 preset language selections. If you need to specify a language that is not on the list, such as Russian, you must type the ISO 639 code for the language, not its name.
> This example is shown in operation in the working example of adding a /Lang entry using Acrobat Pro.

https://www.w3.org/TR/WCAG20-TECHS/PDF16.html

Could you please try with `:lang: (en-US)` or `:lang: en-US` ?
(Sorry I don't have Acrobat Reader installed on Linux)

**Comment by ahus1** [comment]
> Could you please try with `:lang: (en-US)` or `:lang: en-US` ?
no change, still looks empty to me

**Comment by Mogztter** [comment]
I'm reopening this issue, we need to investigate further... :mag_right:

**Comment by Mogztter** [comment]
> I tried the attached PDF language-en.pdf, and it also doesn't show the language. So it's probably only me.

Same for me with Acrobat Reader DC v2019.021.20049

![Capture](https://user-images.githubusercontent.com/333276/68693860-59db9a80-0578-11ea-9f90-7f0eedd6dfd2.PNG)

**Comment by Mogztter** [comment]
According to the specification: 

> Table 28 - Entries in the catalog dictionary

Key | Type | Value
------------ | -------------| -------------
`Lang` | text string | (Optional; PDF 1.4) A *language identifier* that shall specify the natural language for all text in the document except where overridden by language specifications for structure elements or marked content (see 14.9.2, "Natural Language Specification"). If this entry is absent, the language shall be considered unknown.

A language identifier shall either be the empty text string, to indicate that the language is unknown, or a Language-Tag as defined in RFC 3066, Tags for the Identification of Languages.


https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

So it should work...

**Comment by Mogztter** [comment]
I've asked the PDF guru at: https://github.com/Hopding/pdf-lib/issues/236

**Comment by Mogztter** [comment]
> All of this leads me to believe that the inability to view a document's language metadata in Adobe Acrobat Reader DC may be a bug in Acrobat Reader itself. Or perhaps its intended, for some strange reason. But it does not appear to have anything to do with the PDF document itself. Because the issue persists even when viewing the language for a document created by Adobe Acrobat itself, without using any third party libraries.

In short it's the right way to do it but it's not supported in some PDF reader.

**Comment by merenyia** [comment]
Hi, the major problem is that not only is the language attribute empty in Acrobat Reader, but the document also fails to meet WCAG specifications. Screen readers interpret documents with empty language attributes using the OS default language. I'm blind, my Windows default language is set to Hungarian, and the PDF is written in English. When I use exifftool to set the language to 'en-GB,' Adobe Reader's file properties still show the language attribute as empty, and the screen reader reads the English text with a barely understandable Hungarian pronunciation."

**Comment by ggrossetie** [comment]
@merenyia unfortunately it seems like this is an issue with Acrobat Reader. 

>  but the document also fails to meet WCAG specifications

The WCAG specifications for PDF states:



> Specifying the default document language in a PDF document using a /Lang entry
> The natural language used for text in a document is determined in a hierarchical fashion, based on whether an optional /Lang entry is present in any of several possible locations. At the highest level, the document's default language may be specified by a /Lang entry in the document catalog.

> The following code fragment illustrates code that is typical for using the /Lang entry in the document catalog for a document's default language (in this case, US English). (This is typically accomplished by an authoring tool.)

```
 1 0 obj
   << /Type /Catalog
      ...
      /Lang (en-US)
      ...
   >> 
 endobj
```

Source: https://www.w3.org/TR/WCAG20-TECHS/pdf

I believe that's already what we are doing, so I'm not sure what we should do...

**Comment by merenyia** [comment]
Hi,
thank you for the response.
I understand your point; however, I still believe that the issue is not with the Adobe application. When I open a PDF that originally has the 'lang' attribute defined in it, Adobe Acrobat Reader processes it correctly and 'Document Language' attribute is displayed correctly on the properties dialog.

In the case where the 'lang' entry is filled using Exiftool, it does not behave the same way.

Thank you.

**Comment by ggrossetie** [comment]
@merenyia Would it be possible to send me a PDF where the lang attribute is displayed correctly? I want to check if there's something specific we are missing. Thanks!

**Comment by merenyia** [comment]
Thank you indeed, sample pdf 
[accessible-pdf-example.pdf](https://github.com/ggrossetie/asciidoctor-web-pdf/files/13040657/accessible-pdf-example.pdf)
attached.

**Comment by ggrossetie** [comment]
Thanks for sharing a sample PDF.
I found a tiny difference between a PDF generated by Asciidoctor Web PDF and the sample PDF you've provided.

@merenyia Can you please try to open/read the attached PDF? Does it has the correct language (en)? [lang-en.pdf](https://github.com/ggrossetie/asciidoctor-web-pdf/files/13045875/lang-en.pdf)

**Comment by merenyia** [comment]
Hi,
according file/properties the document lang is english. So looks good.
Could you possibly create another one with some textual content so that I can verify if screen readers also recognize the language setting?
Thanks.
