### ISSUE TITLE
Cannot reproduce all examples

### ISSUE THREAD

**Issue by ThomasPrioul** [Mogztter/asciidoctor-pdf.js#119]
Hi,

I'm trying out this tool, so far it's looking good with the default styles.
Then I wanted to try out the given examples (resume, book, etc), however not all documents look the same as in the readme (book and letter), also **the slides one just doesn't work, it says : hljs is not defined.** Do I need to install another global JS library to make it work?

Example with the book (left is mine, right is git repo) :
![book](https://user-images.githubusercontent.com/15314924/68954481-62c0ac00-07c4-11ea-93c7-211b6cc77885.PNG)

Example with letter (pdf on left, html on right which seems ok!) :
![letter](https://user-images.githubusercontent.com/15314924/68954660-c4811600-07c4-11ea-958f-b2ae8bbfc01b.PNG)

For each file I used the following command line:
`asciidoctor-pdf <file>.adoc --template-require ./template.js`

So I was wondering if I'm missing some parameters in the command line or if the CSS files are not updated to what is seen on the repo.
They seem to have margins specified in it but for the book they just get ignored.

I'm using :
- Ubuntu 18.04
- Asciidoctor PDF 1.0.0-alpha.3 using Asciidoctor.js 2.0.3 (Asciidoctor 2.0.9) 
- node 13.1.0.

Can you reproduce the issue?

**Comment by ThomasPrioul** [comment]
Duplicate of issue #36, it was the network connection

**Comment by Mogztter** [comment]
> Duplicate of issue #36, it was the network connection

https://github.com/Mogztter/asciidoctor-pdf.js/pull/113 might improve the situation. We are now using `networkidle0` (on master).

> networkidle0 - consider navigation to be finished when there are no more than 0 network connections for at least 500 ms.

**Comment by ThomasPrioul** [comment]
Yeah I was behind a corporate network blocking most domains...so it's more like what you mentioned in issue #36.

**Comment by Mogztter** [comment]
In the next version, the processor will output the warning and error messages from the console. I'm entirely sure that Chrome will output a warning/error message when a ressource is blocked or cannot be fetched but if it's the case you will see the message on your terminal console.

**Comment by ahus1** [comment]
Another note: the current example reflect the latest development in master. If you convert it using the alpha.3-release the output will look different. 

Hopefully there will be a alpha.4-soon :-) #96

**Comment by ThomasPrioul** [comment]
It did end up looking the same when I used my phone network and not the corporate's.
Anyway I'm happy now, I'll experiment with it more later. I'm looking to customize the title page with a complicated table (typical of a corporate archived document following a defined process) so the template.js capabilities are really interesting me. Seems a lot easier than using a xsl/fop tool chain!
