### ISSUE TITLE
Encoding of & in pdf bookmarks

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-pdf.js#131]
Using alpha 4:

When using an ampersand, `&` in a section title we get the escaped value `&amp;` in the table of contents for the section, when the correct value is `&`

See screenshot of this behaviour:

![image](https://user-images.githubusercontent.com/674783/69472730-bcebed80-0e12-11ea-8cbe-588233146633.png)

The corresponding asciidoc might be, for example:

```adoc
[data-type="issue",data-groups="circuit,added",data-date-created="01/07/2018",data-date-modified="01/07/2018"]
=== C:015 R&I Diagrams in Standard Packages

Where R&I diagrams are provided in a standard package but do not cover every SLD orientation (e.g. top to bottom as well as bottom to top for given voltage levels in the transformer package) it is expected that the R&I diagram should be flipped in AutoCAD.
```

**Comment by Mogztter** [comment]
Thanks for your report, I will add a test to reproduce this issue.

**Comment by Mogztter** [comment]
I can reproduce this issue, though I'm not sure how to fix it.

@mojavelinux is it possible to get the title of a section without HTML entities (or HTML tags)? 
Consider the following AsciiDoc section: ```== _Section 3_: "`Typographic quotes`"``` and I want to get: `Section 3: "Typographic quotes"`.

My idea was to remove HTML tags and replace HTML entities but it seems tedious :disappointed: 

```js
const title = section.getTitle()
    .replace(/<[^>]*>?/gm, '')
    .replace(/&amp;/, '&')
    .replace(/&lt;/, '<')
    .replace(/&gt;/, '>')
    .replace(/&#8220;/, '"')
    .replace(/&#8221;/, '"')
```
