### ISSUE TITLE
Keep heading with next paragraph: broken

### ISSUE THREAD

**Issue by ellipticview** [Mogztter/asciidoctor-pdf.js#144]
basic-example.adoc has a heading that reads:
```
=== Heading that should join paragraph on next page
```
File basic-example.pdf on github does indeed show that this works.

I installed node 12.13.1 (latest LTS) and this application. Downloaded basic-example.adoc and used this as my first example. The heading is the last line on page 8 (instead of the first line on page 9).

**Comment by Mogztter** [comment]
The commit https://github.com/Mogztter/asciidoctor-pdf.js/commit/81faed9d347bbbe60835a27405bf7e50f47d5a3a is on master but not yet released that's why you don't have the same behavior with the latest release 1.0.0-alpha.4.

**Comment by Mogztter** [comment]
Version [https://github.com/Mogztter/asciidoctor-pdf.js/releases/tag/v1.0.0-alpha.4](1.0.0-alpha.4) was released on 2019-11-17.

@ellipticview Please give it a try and reopen this issue if the bug is still not fixed.
