### ISSUE TITLE
watch mode generates pdf instead of html in html file

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-pdf.js#145]
I'm enjoying testing asciidoctor-pdf.

Using watch mode by itself generates no file with a `pdf` extension but does generate a `pdf` with the file name ending in `html`.

For example, I thought I'd try making a cheat sheet for Asciidoctor based on the Snyk one. I was trying to figure out how watch mode and preview worked together:

```bash
asciidoctor-pdf -w --template-require ./snyk/template.js asciidoctor-cheat-sheet.adoc
```

![image](https://user-images.githubusercontent.com/674783/71378125-8aa8f800-262b-11ea-82a5-c8785af9edd4.png)

I expected that watch mode would continuously re-generate both the html and pdf output with their relevant extensions.

**Comment by Mogztter** [comment]
It should be the case as the watch option simply watch a list of files and regenerate the PDF if a change is detected.
