### ISSUE TITLE
watch and preview are incompatible

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-pdf.js#146]
I thought that using both `-w` and `--preview` would be effectively provide a "LiveReload" within the Chromium window.

In fact the options are exclusive so when used together the watch no longer occurs and there is no change to the browser window when the source file changes.

I'm not sure if it's possible to have this, I think that's probably what users might expect or at least what I would like. I would like to write my document in one window/monitor and see the changes occur to the html in the other window/monitor.

I guess this could also be done in other ways..

**Comment by Mogztter** [comment]
It's a bug 🐞
