### ISSUE TITLE
API compatibility with asciidoctor-pdf Ruby version

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-pdf.js#155]
I wanted to recommend this project as a drop-in for the Ruby `asciidoctor-pdf` for the vscode extension (see this issue https://github.com/asciidoctor/asciidoctor-vscode/issues/239) but found it didn't quite work.

The Ruby version has the following:

```bash
 -o, --out-file FILE              output file (default: based on path of input file); use - to output to STDOUT
```
Whereas the js version has:

```bash
  --out-file, -o          output file (default: based on path of input file) use '' to output to STDOUT         [string]
```

Would you be receptive to using `-` to enhance compatibility and portability with the Ruby version?

**Comment by danyill** [comment]
I may be getting this wrong. 

I think `asciidoctor-pdf` Ruby supports the option `-` being passed by itself (not in connection with `-o`) for reading from `STDIN` but currently the js version doesn't support this.

It doesn't seem to be documented for the Ruby version either but is depended on in the asciidoctor-vscode extension ([here](https://github.com/asciidoctor/asciidoctor-vscode/blob/fedc482892f2eb2c9fb649e528066c07807cf3f7/src/commands/exportAsPDF.ts#L61))

**Comment by danyill** [comment]
Ah. The documentation is in the user manual: https://asciidoctor.org/docs/user-manual/#piping-content-through-the-cli

**Comment by Mogztter** [comment]
It should work both ways, reading from stdin and writing to stdout.

**Comment by Mogztter** [comment]
Actually there's an issue here:

https://github.com/Mogztter/asciidoctor-pdf.js/blob/3da382ef961dc08ce5f7e86df216251c4407d2c3/lib/converter.js#L101

`pdf` object is an [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Objets_globaux/Uint8Array) and `toString` will return a string representing the specified array and its elements (not the actual data).
We probably need to convert it to a binary string:

```js

function convertUint8ArrayToBinaryString(u8Array) {
  var i, len = u8Array.length, b_str = "";
  for (i=0; i<len; i++) {
    b_str += String.fromCharCode(u8Array[i]);
  }
  return b_str;
}
```

@danyill To be clear, you want to write the PDF to stdout? or you want to read the AsciiDoc content from stdin? or maybe both?

**Comment by danyill** [comment]
Well at the moment the vs-code extension only uses stdin to pipe the Asciidoc contents in and then writes to a file. Perhaps it makes sense to have stdout too (I'm not sure).

I've been looking at the way reading from stdin is supported. It seems to require that `-` is the last argument provided, see requires that this be the _last_ option in the command line (i.e. that it end with `-`).

See:
https://github.com/asciidoctor/asciidoctor-cli.js/blob/693a9910d4d0a59103b7590ea57dbddf197d4135/lib/options.js#L223-L237

I did a PR with "something like" the changes that are necessary.

**Comment by danyill** [comment]
Thanks @Mogztter
