### ISSUE TITLE
Please document usage how to use Asciidoctor extensions

### ISSUE THREAD

**Issue by rohel01** [Mogztter/asciidoctor-pdf.js#166]
The Asciidoctor ecosystem features numerous helpful extensions.

Which can be used with asciidoctor-pdf.js?
How can I activate them ? CLI arguments? Custom javascript?

Documentation should be extended to cover theses questions

**Comment by Mogztter** [comment]
@rohel01 I would love your feedback on #204

**Comment by rohel01** [comment]
Seems good, I just made a minor comment about vocabulary
