### ISSUE TITLE
Upgrade to Paged.js 0.1.37

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/asciidoctor-pdf.js#168]
https://gitlab.pagedmedia.org/tools/pagedjs/compare/v0.1.35...v0.1.37

This version will remove the error/warning message during the installation:
- https://github.com/Mogztter/asciidoctor-pdf.js/issues/162
- https://github.com/Mogztter/asciidoctor-pdf.js/issues/165

**Comment by oncletom** [comment]
It will also fix the looping issue you encountered in https://github.com/Mogztter/asciidoctor-pdf.js/issues/165#issuecomment-584337646, via [update page count](https://gitlab.pagedmedia.org/tools/pagedjs/merge_requests/85).

**Comment by Mogztter** [comment]
Oh nice, let's do it then! :rocket:

**Comment by Mogztter** [comment]
> It will also fix the looping issue you encountered in #165 (comment), via update page count.

Unfortunately it does not fix the looping issue but it does avoid a repaint so the preview is less "sluggish" and it's actually looping faster! :laughing: 

![loop-crazy](https://user-images.githubusercontent.com/333276/74937693-df2ee080-53ec-11ea-8c8b-abe3bb4719bb.gif)
