### ISSUE TITLE
Rendering DOT graphs

### ISSUE THREAD

**Issue by Patryk27** [Mogztter/asciidoctor-pdf.js#170]
Hi! :-)

Is there a way for `asciidoctor-pdf.js` to automatically convert inline `dot` code into images?
I've found https://github.com/mogztter/asciidoctor-kroki, but I'm not sure how to use it here.

Thanks;

**Comment by Mogztter** [comment]
Hi Patryk!

> Is there a way for asciidoctor-pdf.js to automatically convert inline dot code into images?
> I've found https://github.com/mogztter/asciidoctor-kroki, but I'm not sure how to use it here.

Asciidoctor PDF.js can use Asciidoctor extensions. The documentation is not there yet (see https://github.com/Mogztter/asciidoctor-pdf.js/issues/166) but you can load an extension from the CLI.

If `asciidoctor-kroki` is available in your _node_modules_ then the following command use Kroki to convert your dot diagram:

```
$ asciidoctor-pdf test.adoc -r asciidoctor-kroki
```

```console
$ dir node_modules/asciidoctor-kroki
dist  LICENSE  package.json  README.md
```

```console
$ cat test.adoc
= Test

[graphviz]
....
digraph foo {
  node [style=rounded]
  node1 [shape=box]
  node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
  node3 [shape=record, label="{ a | b | c }"]

  node1 -> node2 -> node3
}
....
```

And here's the result: [test.pdf](https://github.com/Mogztter/asciidoctor-pdf.js/files/4245367/test.pdf)

**Comment by Patryk27** [comment]
Wowo, this is amazing - thanks :-)
