### ISSUE TITLE
Error: Unable to generate the PDF 

### ISSUE THREAD

**Issue by tobiasd** [Mogztter/asciidoctor-pdf.js#173]
I've just installed asciidoctor-pdf.js on Linux. When I compile a adoc file I get the error message 

    Unable to generate the PDF - Error: ReferenceError: URL is not defined

Here is the version information of my installation

```
Asciidoctor PDF 1.0.0-alpha.7 using Asciidoctor.js 2.1.1 (Asciidoctor 2.0.10) [https://asciidoctor.org]
Runtime Environment (node v8.17.0 on linux)
CLI version 3.2.0
```

**Comment by Mogztter** [comment]
Hello @tobiasd 

Could you please share the command you are typing? And if possible a sample document that reproduces this issue.

You can add `--preview` to open the preview in a headfull instance of Chrome. If you open the developer console you might have more information.

Thanks!

**Comment by tobiasd** [comment]
Hey, thanks for your quick reply!

> Could you please share the command you are typing? And if possible a
> sample document that reproduces this issue.

Sure. Even something basic as this `test.adoc`

```
= Test

Test
```

compiled with

```
/usr/lib/node_modules/asciidoctor-pdf/bin/asciidoctor-pdf test.adoc
```

produces this error. The original document I tried was more complex and so far compiled with the ruby asciidoctor-pdf tool. As that is still installed I'm calling the program directly from the global node modules.

> You can add `--preview` to open the preview in a headfull instance of
> Chrome. If you open the developer console you might have more
> information.

The preview chromium is opened with the "about:blank" page.

**Comment by Mogztter** [comment]
What version of Node.js are you using?
I'm using `URL`, it might only be available in Node > 10, I was not aware of that. Could you try updating to the latest LTS?

**Comment by tobiasd** [comment]
See above I had some really old version installed, I use literally one other tool based on node on my system, that I now remember had problems updating some time ago. After updating the APT sources to node 12 PDF generation is now working.

```
Asciidoctor PDF 1.0.0-alpha.7 using Asciidoctor.js 2.1.1 (Asciidoctor 2.0.10) [https://asciidoctor.org]
Runtime Environment (node v12.16.1 on linux)
CLI version 3.2.0
```

Thank you very much for your help! And luckily the other tool fixed their problems with updating node as well *phew*

**Comment by Mogztter** [comment]
Thanks for the follow-up!
Since Node.js 8 is EOL, I don't think we want to patch the code to support Node.js 8.

But I will reopen this issue because I think we should update the engine in the `package.json`:

https://github.com/Mogztter/asciidoctor-pdf.js/blob/38fc0d9a339280b77e74e6820e4ed4aeae2dabe5/package.json#L6
