### ISSUE TITLE
Use other delimiter for stylesheet override

### ISSUE THREAD

**Issue by makon** [Mogztter/asciidoctor-pdf.js#189]
I would suggest to use a different delimiter than `;` for accepting multiple stylesheets, e.g.  `,`
Because `;` is also a command delimiter for shell so it can easily lead to `command not found` errors, which is not obvious and can take a while to understand the reason. e.g.
```
$ asciidoctor-pdf -a stylesheet=asciidoctor.css;document.css mydoc.adoc
...
bash: document.css: command not found
```
At least adjust the example in the readme:
> The stylesheet attribute can accept multiple semi-colon delimited values (without spaces). For example -a stylesheet=asciidoctor.css;override.css. This could be used to begin with a base stylesheet and then apply supplementary content.

**Comment by Mogztter** [comment]
Hello @makon 

That's a good point.
I don't recall why we chose `;` as a separator with @mojavelinux. I can see that we are using `,` in the `--require` option...
Here's the upstream issue: https://github.com/asciidoctor/asciidoctor/issues/3471

> At least adjust the example in the readme:

Indeed, we need to update the documentation.

**Comment by makon** [comment]
Hi @Mogztter,

I can create a PR for the documentation update. I would also like to add an example for the default css stylesheet options from #104 and #105. If it's okay with you.

**Comment by Mogztter** [comment]
Sure, that would be great :+1:

**Comment by mojavelinux** [comment]
Here's what we learned about delimiters for this sort of thing: https://github.com/asciidoctor/asciidoctor-pdf/issues/1250

The lesson is, you need to be flexible since different operation systems and shells have different reserved characters. Generally, a comma seems to be a safe bet.

**Comment by Mogztter** [comment]
@mojavelinux Thanks for your input.
So you don't mind if we switch from semicolon to colon:

**New delimiter**
```
-a stylesheet="asciidoctor.css,override.css"
```

**Comment by mojavelinux** [comment]
I think you mean comma. In that case, I agree it's a good move.

**Comment by Mogztter** [comment]
> I think you mean comma. In that case, I agree it's a good move.

Ooops, yes 👍

**Comment by Mogztter** [comment]
@makon I think we should support both and add a deprecation warning, what do you think? I don't want to introduce a breaking change even if we are still in beta and it's pretty straightforward to add backward compatibility.
