### ISSUE TITLE
Use the object tag for svg images rather than img tag

### ISSUE THREAD

**Issue by gostone** [Mogztter/asciidoctor-pdf.js#214]
If you display an SVG in HTML with the \<img\> tag, it doesn't render resources such as <image> tags inside the SVG. 

The simple fix is to use an \<object\> tag instead. I don't know of any issues with that.

You can do this with a custom template file, but because you can't extend the default template the result becomes unusable.

**Comment by Mogztter** [comment]
>  you display an SVG in HTML with the  tag, it doesn't render resources such as  tags inside the SVG.

Not sure I quite understand what you mean. Could you please post a screenshot with the current result and the expected result?

> The simple fix is to use an tag instead. I don't know of any issues with that.

We inherit from the built-in HTML 5 converter from Asciidoctor core. So if we do change something we will probably do it upstream (unless it's a specific issue with the PDF backend).

> You can do this with a custom template file, but because you can't extend the default template the result becomes unusable.

It's actually possible to extend the default converter. See: https://github.com/Mogztter/asciidoctor-pdf.js/pull/133
This feature is not documented (yet) but you can find an example in the tests: https://github.com/Mogztter/asciidoctor-pdf.js/pull/133/files#diff-d80102e55a291a3b3061ed04192450c3R12

Once you wrote your custom converter you should use the `--require` option to require it and `--backend` to set the backend name (in this example I'm using the name `custom-web-pdf`).

**Comment by gostone** [comment]
Sorry @Mogztter, the tags in my comment didn't format properly. Fixed now, and hopefully a bit clearer.

I'm using SVGs that include other SVGs using the \<image\> tag. The includes don't work if you use the \<img\> tag. 

I've attached three files:

pink-rectangle.svg draws a pink rectangle
composite.svg draws a grey circle and includes pink-rectangle.svg
viewsvg.html displays composite.svg two ways, with \<object\> and \<img\>

The \<img\> version doesn't show the included pink rectangle

[svg-display-example.zip](https://github.com/Mogztter/asciidoctor-pdf.js/files/4498914/svg-display-example.zip)

**Comment by Mogztter** [comment]
In this case you should use inline SVG:

```
= Test

image::composite.svg[options=inline]

image::composite.svg[]
```

![pdf](https://user-images.githubusercontent.com/333276/79691813-e1cd7b00-8261-11ea-9aa4-07d760ee78aa.png)

[test.pdf](https://github.com/Mogztter/asciidoctor-pdf.js/files/4499479/test.pdf)

**Comment by gostone** [comment]
Thank you! I'm not sure why that should fix it but it has. You're welcome to close this issue if you like.

**Comment by Mogztter** [comment]
> Thank you! I'm not sure why that should fix it but it has. 

The `inline` option will inline the `<svg>` file in the HTML (instead of using an `<img>` tag).

> You're welcome to close this issue if you like.

:+1:
