### ISSUE TITLE
Add admonitions example

### ISSUE THREAD

**Issue by matklad** [Mogztter/asciidoctor-pdf.js#23]
This is googlable, but it's better to have this in one (all?) of the examples.

* add `:icons: font` to doc attributes
* add 

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
```

to the `<head>` in the template.js

**Comment by Mogztter** [comment]
Good idea!
We could also demonstrate how to use Font Awesome 5 (but that's probably another topic).
