### ISSUE TITLE
{indir} is not replaced in the content

### ISSUE THREAD

**Issue by oncletom** [Mogztter/asciidoctor-pdf.js#26]
Hello,

I was wondering what should be done to make the `{indir}` variable to be interpolated? I thought it was bound to `-a safe=unsafe` or `-a experimental` but it does not seem so.

I don't know if it's a limitation of this flavour of Asciidoctor.

**Comment by johannesjh** [comment]
note: a more polished version of the extension can be found here:
https://github.com/johannesjh/asciidoctor-indir_ext

**Comment by oncletom** [comment]
Cool, I got my answer, thanks!
