### ISSUE TITLE
`--watch` option leaks browsers

### ISSUE THREAD

**Issue by matklad** [Mogztter/asciidoctor-pdf.js#27]
Don't have time to write a detail bug-report, but TL;DR is that running

```
./node_modules/asciidoctor-pdf.js/bin/asciidoctorjs-pdf -v ./src/slides.adoc --template-require ./src/template.js  --watch
```

Eventually allocates 10GB of memory. Don't know what exactly is allocated: `htop` does not show that any particular process allocates a lot of memory, but the total mem usage is high, and system becomes unresponsive. 

Hypothesis: we leave behind some processes, which don't use a ton of memory by themselves, thus dodging the `htop`.

**Comment by matklad** [comment]
Yep, there's a ton of Chromium processes in background.

**Comment by Mogztter** [comment]
Nice catch, we should probably use a try/finally and close the browser: https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#browserclose

**Comment by matklad** [comment]
I guess we should do both: closing resources is always a good idea :-)

**Comment by Mogztter** [comment]
:+1: 
Let me know if you want to submit a pull request, otherwise I will do it later today :wink:

**Comment by matklad** [comment]
>Let me know if you want to submit a pull request, o

I want, but I absolutely don't have time :-)

**Comment by Mogztter** [comment]
No worries I will take care of it, thanks for taking the time to report this issue :+1:
