### ISSUE TITLE
Support of MathML 

### ISSUE THREAD

**Issue by ahus1** [Mogztter/asciidoctor-pdf.js#64]
Out of curiosity I tried out how to enable Math support. The following quick hack worked surprisingly well using the "cheat-sheet" example.

I added to template.js the following snippet (copy and paste from AsciiDoc HTML document just before end of body tag):

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  messageStyle: "none",
  tex2jax: {
    inlineMath: [["\\(", "\\)"]],
    displayMath: [["\\[", "\\]"]],
    ignoreClass: "nostem|nolatexmath"
  },
  asciimath2jax: {
    delimiters: [["\\$", "\\$"]],
    ignoreClass: "nostem|noasciimath"
  },
  TeX: { equationNumbers: { autoNumber: "none" } }
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_HTMLorMML"></script>
```

and some math to the maven-security-cheat-sheet.adoc file: 

```
:stem: latexmath

[latexmath]
++++
\sqrt{4} = 2
++++
```

And I get a nice output: 

![math](https://user-images.githubusercontent.com/3957921/65778648-98430480-e146-11e9-82fc-da1e8ebdac97.png)

I wonder: 
* should I add this to the default `templates.js` as a pull request so that creating PDFs with math works out of the box? Anything I should consider in the PR? 
* is there a way to extend the existing template? Or would the standard process copy the standard template first and the modify it?

Any advice is welcome, and I'm happy to provide a PR.

**Comment by Mogztter** [comment]
> should I add this to the default templates.js as a pull request so that creating PDFs with math works out of the box?

Yes I think it would be great.

> Anything I should consider in the PR?

We should use the same condition as Asciidoctor core to enable Math support.
We might want to use a local install of MathJax to be "offline first", what do you think?

> is there a way to extend the existing template? 

That's a good question!
To give a little bit of history, the goal of the default template is to provide a way to generate a "standard" PDF from an AsciiDoc document (similar to what Asciidoctor Ruby PDF is doing).
I still think that if you want to generate a cheat sheet or a presentation you will need to provide your own template.
In an ideal world, we should be able to use the same template and produces different kind of PDFs using only CSS but in practice it can be hard! (see http://www.csszengarden.com/)

To answer your question, no it's not currently possible to extend an existing template.
Do you have a concrete example in mind or was it an theoretical question?

> Or would the standard process copy the standard template first and then modify it?

For now yes.
You can start from scratch or take inspiration from this repository.
Having said that, I think you should first try to customize the output using CSS and/or Asciidoctor extensions.

> Any advice is welcome, and I'm happy to provide a PR.

Are you familiar with the JavaScript ecosystem/environment?
I need to write a contributing guide but in the meantime you should be able to build the project using `npm`.
Once the project is cloned, you can install the dependencies using:

```console
$ npm i
```

And then you run the linter and the tests:

```console
$ npm run lint
$ npm t
```

If you could add tests for this new feature that would be great: https://github.com/Mogztter/asciidoctor-pdf.js/blob/master/test/templates_test.js

And if you have any questions or suggestions, please let me know. This project is still at an early stage, so all ideas are welcome 😉

**Comment by ahus1** [comment]
Extending a template would have been an option if you considered it out of scope for the standard template. As the plan is now to integrate it in the standard template there is no need for extension. 

I'm OK with JavaScript/npm, I'll have a look around. Thank you for the hint about the tests. 

I saw a "cdnjs.cloudflare.com" in the template.js, at first glance it is used for syntax highlighting. Therefore I wasn't considering offline support for mathjax. Please let me know if you would accept an online-only version for mathjax.

Expect a PR sometime during Hacktober.

**Comment by Mogztter** [comment]
> Please let me know if you would accept an online-only version for mathjax.

Sure, it was just something to consider since the CLI could be run in a restricted environment.
But we could implement it later if we think it's worth it.

> Expect a PR sometime during Hacktober.

Excellent, thanks 👍
