### ISSUE TITLE
Feedback regarding styling capabilities

### ISSUE THREAD

**Issue by Ablu** [Mogztter/asciidoctor-pdf.js#88]
Hi,

I now spent some time theming the document in order to get the same result as the purely pagedjs-cli based solution. I think there are some easy ways to improve the current situation:

* currently it is not possible to disable the default CSS. While this makes it easy to get started, it can really be a pain if you want to completely customize the page. You do not only need to understand your own CSS, but also the default CSS. Some way to disable the default CSS would be great :)
* There are some very specific rules in the default CSS which make it hard to override certain aspects of the default theme. For example, the font-name "Noto Serif" is mentioned in 5 places, changing the text-color or font-size is... hard :P. I think in many cases some CSS variables could greatly simplify the creation of themes inheriting from the default theme.

**Comment by Mogztter** [comment]
> currently it is not possible to disable the default CSS. While this makes it easy to get started, it can really be a pain if you want to completely customize the page. You do not only need to understand your own CSS, but also the default CSS. Some way to disable the default CSS would be great :)

At first, I thought it was a good idea but I will just replace the default stylesheet when the user provide a custom stylesheet.

> There are some very specific rules in the default CSS which make it hard to override certain aspects of the default theme. For example, the font-name "Noto Serif" is mentioned in 5 places, changing the text-color or font-size is... hard :P. I think in many cases some CSS variables could greatly simplify the creation of themes inheriting from the default theme.

Since we are using a modern browser we could use [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).
Having said that I think we should create a dedicated project to produce custom themes (similar to what Asciidoctor core is doing) where we could split the styles per "component" and even use Sass or Less.

**Comment by oncletom** [comment]
It makes me think of this:

```bash
$ asciidoctor-pdf -a stylesheet=asciidoctor-pdf/variables.css  -a stylesheet=my-variables.css -a stylesheet=asciidoctor-pdf/themes/default.css ...
```

Does it make sense?

If we can load files using npm modules too, it would be easier to combine components without too much trouble.

**Comment by oncletom** [comment]
[`require.resolve()`](https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_require_resolve_request_options) at your service!

**Comment by Mogztter** [comment]
I just asked Dan and we should use the following syntax (separated by semi-colons):

```
$ asciidoctor-pdf -a stylesheet="npm://asciidoctor-pdf/css/document.css;custom.css" document.adoc
```

Asciidoctor PDF is already using this syntax to include multiple font directories with `pdf-fontsdir`.

@oncletom What do you think about the `npm://` prefix? Is there a convention to reference a Node module?

**Comment by oncletom** [comment]
I have never seen the `npm://` prefix in other libs. Most of them rather use an "include path" option to resolve a relative path from a list of paths.

Example:

- `node-sass` has an `includePath` option; cf. [github.com/sass/node-sass#includepaths](https://github.com/sass/node-sass#includepaths)
- [`postcss-import`](https://github.com/postcss/postcss-import) adds a lookup into web_modules, node_modules and local folders to PostCSS
- `parcel` uses a `~` prefix (but I find this weird as `~` is also an alias for `$HOME` on some OSes); cf. parcel-bundler/parcel#1800

**Comment by Mogztter** [comment]
> Most of them rather use an "include path" option to resolve a relative path from a list of paths.

I'm a bit divided on adding an "include path" option. I think it's mainly because I tend to prefer explicit over implicit.
Do you know how they include the global `node_modules` directory without using an absolute path?

> I have never seen the npm:// prefix in other libs. 

I guess we could use `node_modules` as a prefix and if the package does not exist on the local `node_modules`, we should try to find it on the global `node_modules`.
It's a bit of magic but I think it's the expected behavior.
Does it sound good to you?

> parcel uses a ~ prefix (but I find this weird as ~ is also an alias for $HOME on some OSes); cf. parcel-bundler/parcel#1800

I don't like it either. I think they do it because a package name cannot contain the symbol `~` but in my opinion it's a bad choice.

**Comment by Mogztter** [comment]
We are already using `require.resolve` in the Asciidoctor CLI: https://github.com/asciidoctor/asciidoctor-cli.js/blob/b93ae03695514447d33832cdaebb411a2ae6ef43/lib/invoker.js#L102-L112

So we should probably use more or less the same strategy for stylesheet.
I think we should create 2 issues:

- Allow to specify multiple stylesheets (values are separated by semicolon)
- Resolve stylesheets from node_modules and local folders

> currently it is not possible to disable the default CSS. 

I've fixed this issue in https://github.com/Mogztter/asciidoctor-pdf.js/pull/93

**Comment by Mogztter** [comment]
Both issues are now resolved:

- https://github.com/Mogztter/asciidoctor-pdf.js/issues/104
- https://github.com/Mogztter/asciidoctor-pdf.js/issues/103

@Ablu If you still encounter some limitations when styling a document, please feel free to create a new issue.
