### ISSUE TITLE
Publish the next alpha version v1.0.0-alpha.4

### ISSUE THREAD

**Issue by ahus1** [Mogztter/asciidoctor-pdf.js#96]
A lot of changes accumulated over the last month. I'd be happy to see a next alpha release soon to make it easier for me to test it in collaboration with others.

**Comment by Mogztter** [comment]
Indeed, I'm currently drafting the release note :smile:

**Comment by Mogztter** [comment]
I've added a few issues I want to fix before publishing the next alpha: https://github.com/Mogztter/asciidoctor-pdf.js/milestone/1

**Comment by Mogztter** [comment]
I think we are ready!

@ahus1 What about 1.0.0-beta.1 ? :thinking:

**Comment by ahus1** [comment]
I'd go for another alpha; too many things changed recently.

**Comment by Mogztter** [comment]
Version 1.0.0-alpha.4 is out:

- https://github.com/Mogztter/asciidoctor-pdf.js/releases/tag/v1.0.0-alpha.4
- https://www.npmjs.com/package/asciidoctor-pdf/v/1.0.0-alpha.4

Tweet is coming :bird:
